version: '3.7'
services:
  knubot:
    build:
      context: app
    volumes:
        - ./log:/app/log
    environment:
      TZ: Asia/Tokyo
      BOT_TOKEN: 
    networks:
      app_net:
    restart: always

  postgres:
    image: postgres:13
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres
    networks:
      app_net:
    restart: always

networks:
  app_net:
    name: knubot_net
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.31.0.0/24

volumes:
    postgres_data:
